### ISSUE TITLE
InventoryController

### ISSUE THREAD

**Issue by drewburlingame** [RHeimbeck/SimpleInventory#2]
A couple of questions about this controller
1. POST:  what does an example of this url look like: api/inventory/{InventoryItem}?
2. DELETE: throws a 404 if the item no longer exists.  is that intended?  if so, why?

**Comment by RHeimbeck** [comment]
Hi Drew,
1. Yes, Example of POST would be 'api/inventory/{InventoryItem}'  - though
   now in review I think the parameter would more aptly be named just "{item}".
2. Ah yes - although 404 is sometimes used in these cases, the more
   standard response would be 204 - "No Content" - the server successfully
   processed the request, but is not returning any content.
