### ISSUE TITLE
DataExpirer

### ISSUE THREAD

**Issue by drewburlingame** [RHeimbeck/SimpleInventory#3]
What race conditions exist with the current approach?  how would you fix them?

**Comment by RHeimbeck** [comment]
Hi Drew,
    Hmmmm.  Here is what I do know: Race conditions could exist for access
to the one common data repository; 1) simultaneous user accesses, each on
separate threads, and 2) the 'expiration' service thread waking up
periodically and removing expired data items from the inventory.  I thought
I had provided adequate thread exclusion to the data repository by adding
thread locking blocks around the Add and Delete access methods.  !!*\* Now
that I think about this I should have the same thread locking blocks around
the two data reading methods.  The potential race condition vulnerability
would be if one thread was reading the data, and then another thread could
come in, lock the data, and then add or delete items.  To be fully thread
safe, I need to add thread locking on the two 'Get' data read methods.
    Good Catch!  Am I missing something else - another race condition??

Thank you,
Reid Heimbeck

**Comment by RHeimbeck** [comment]
Hi Drew,
    I hope I can have a few moments of your time to get your feedback on this project, and what parts of it or my answers did not meet your expectations.  That way I can make this a learning exercise and pick you some expert pointers from you.  Can you please tell me what I missed in  the project and/or my response?

Thank you!
